name: auto_exporter_annotation
description: This library is some annotations for auto_exporter library, see auto_exporter for more information.
version: 1.0.2
homepage: https://github.com/normidar/auto_exporter_pkgs

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
