dependencies:
  auto_exporter_annotation: ^1.0.1
  flutter:
    sdk: flutter
description: an application by normidar.
dev_dependencies:
  auto_exporter:
    path: ../../
  build_runner: ^2.4.6
  build_test: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  flutter: ">=1.17.0"
  sdk: ">=3.1.5 <4.0.0"
homepage: null
name: flutter_example
version: 0.0.1
