targets:
  $default:
    builders:
      auto_exporter:
        options:
          default_export_all: true # default is true, if false, auto_exporter will not export any files by default and you will need to use the @AutoExport() annotation to export files.
          project_name: dart_example
          sub_packages:
            - auto_exporter_annotation