name: dart_example
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.1.5

dependencies:
  auto_exporter_annotation: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  auto_exporter:
    path: ../../
  build_runner: ^2.4.6
  build_test: ^2.2.0
