---
dependencies:
  auto_exporter_annotation: ^1.0.1
description: A starting point for Dart libraries or applications.
dev_dependencies:
  auto_exporter:
    path: ../../
  build_runner: ^2.4.6
  build_test: ^2.2.0
  lints: ^2.0.0
  test: ^1.21.0
environment:
  sdk: ^3.1.5
name: dart_example
version: 1.0.0
